### ISSUE TITLE
How can I save the figures of result？

### ISSUE THREAD

**Issue by chjq201410695** [WillKoehrsen/feature-selector#11]

**Comment by WillKoehrsen** [comment]
If you are running this in a Jupyter Notebook, you can just right click on the plot and `save image`. If you are running this from the command line, you'll probably need to type `plt.show()` which should open the plot in a pop-up window. You can then save the resulting plot. I hope that helps!

**Comment by chjq201410695** [comment]
Thanks for your response. I run it in jupyter notebook. but I find the saved image is too blur if it is enlarged. So I wonder how can I use the plot.savefig() function in your projects.

**Comment by WillKoehrsen** [comment]
You can call `plt.savefig(fname)` after creating the plot in the Jupyter Notebook. By default, this will save the last plot produced. Read up on [the documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html) for more information, such as how to control the image quality (dpi).

**Comment by chjq201410695** [comment]
> You can call `plt.savefig(fname)` after creating the plot in the Jupyter Notebook. By default, this will save the last plot produced. Read up on [the documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html) for more information, such as how to control the image quality and resolution (dpi).

Thanks， it is very helpful！
