### ISSUE TITLE
Question about 'Zero Importance Features' method

### ISSUE THREAD

**Issue by prodigyxiao** [WillKoehrsen/feature-selector#12]
Hi,
When I was trying the method 'identify_zero_importance', I have met the error below:
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

However, the 'Usage' notebook does not mentioned anything about treating NaN values.
And it is common to have missing value for most datasets.

So, my question is do I need to remove all the rows which contains missing value before calling the 'identify_zero_importance' method?

Thank you very much for devloping such a convinient package!

Best wishes.

**Comment by WillKoehrsen** [comment]
You'll have to `impute` the missing values in your dataset before using the Feature Selector. This can be done easily with the `SimpleImputer` class in Scikit-Learn. [Here is the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html).

**Comment by prodigyxiao** [comment]
Thank you very much for your rapid reply.

By the way, which stragegy in the `SimpleImputer` do you suggest for better using your `feature-selector` package?

Best wishes~

**Comment by WillKoehrsen** [comment]
There is no generally agree-upon consensus, but I use "median" imputation. This fills the missing values in a column with the median value in the column.

**Comment by prodigyxiao** [comment]
OK.
Thanks a lot!

**Comment by WillKoehrsen** [comment]
No problem. Let me know if you have other questions about the Feature Selector!
