### ISSUE TITLE
save as csv

### ISSUE THREAD

**Issue by HIN0209** [WillKoehrsen/feature-selector#2]
@WillKoehrsen 
Thank you for providing an interesting project. 

At the last line of Future_selector_Usage, I would like to request to save as a csv file (after removing unnecessary features), so that I can use it for machine learning. It must be very easy by to_csv method of pandas, but I cannot specify.

**Comment by WillKoehrsen** [comment]
After identifying the features to remove, you can drop them using the `remove` method.  This returns a dataframe with the features removed that you can save to a csv using `to.csv`!

**Comment by WillKoehrsen** [comment]
The serial numbers are the index added by Pandas when you use `.to_csv`. To not add these in when saving a file use `.to_csv(index = False)`. However, if you have an index that you need to save, then don't use this syntax! 

Thanks for raising this issue and hopefully it might be helpful to others!
