### ISSUE TITLE
LightGBMError: Multiclass objective and metrics don't match

### ISSUE THREAD

**Issue by ansin218** [WillKoehrsen/feature-selector#20]
Does the library have capabilities to handle continuous target variables? I am trying to pass a variable with 600,000 records with integer values between 0-180 and I stumble upon this:

```
Traceback (most recent call last):

  File "<ipython-input-2-285466e856ff>", line 1, in <module>
    runfile('C:/Users/ankurs/nutella.py', wdir='C:/Users/ankurs')

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ankurs/nutella.py", line 89, in <module>
    churnFeatures = TreeFeatureSelection(x, targetChurn)

  File "C:\Users\ankurs\FeatureEngineering.py", line 22, in TreeFeatureSelection
    n_iterations = 10, early_stopping = True)

  File "C:\Users\ankurs\feature_selector.py", line 311, in identify_zero_importance
    early_stopping_rounds = 100, verbose = -1)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\sklearn.py", line 700, in fit
    callbacks=callbacks)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\sklearn.py", line 502, in fit
    callbacks=callbacks)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\engine.py", line 192, in train
    booster = Booster(params=params, train_set=train_set)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\basic.py", line 1487, in __init__
    train_set.construct().handle,

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\basic.py", line 985, in construct
    categorical_feature=self.categorical_feature, params=self.params)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\basic.py", line 771, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\basic.py", line 835, in __init_from_np2d
    ctypes.byref(self.handle)))

  File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\lightgbm\basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))

LightGBMError: Multiclass objective and metrics don't match
```

I also tried googling and adding multi_logloss eval metrics to the LGBMClassifier and LGBMRegressor but no luck.

**Comment by alibaltschun** [comment]
@ansin218 did you find the solutions?

**Comment by ansin218** [comment]
@alibaltschun Unfortunately, not yet.

**Comment by alibaltschun** [comment]
i found the problem,
coz we installing the up to date packages.

try to downgrade lightgbm
`pip install --user lightgbm==2.1.1`

if still error try to  downgrade seaborn too
`pip install --user seaborn==0.8.1`

**Comment by ansin218** [comment]
The first solution itself worked. Thanks a ton, mate!

**Comment by alibaltschun** [comment]
welcome @ansin218

**Comment by chengjianhong** [comment]
@ansin218 I have downgraded the lightgbm and seaborm, but it stll has the same error.

> ---------------------------------------------------------------------------
> LightGBMError                             Traceback (most recent call last)
> <ipython-input-47-47b00f66835b> in <module>
>       1 fs.identify_zero_importance(task = 'classification', eval_metric = 'auc', 
> ----> 2                             n_iterations = 10, early_stopping = True)
> 
> <ipython-input-36-00393c102e13> in identify_zero_importance(self, task, eval_metric, n_iterations, early_stopping)
>     309                 model.fit(train_features, train_labels, eval_metric = eval_metric,
>     310                           eval_set = [(valid_features, valid_labels)],
> --> 311                           early_stopping_rounds = 100, verbose = -1)
>     312 
>     313                 # Clean up memory
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
>     698                                         verbose=verbose, feature_name=feature_name,
>     699                                         categorical_feature=categorical_feature,
> --> 700                                         callbacks=callbacks)
>     701         return self
>     702 
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
>     500                               verbose_eval=verbose, feature_name=feature_name,
>     501                               categorical_feature=categorical_feature,
> --> 502                               callbacks=callbacks)
>     503 
>     504         if evals_result:
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
>     190     # construct booster
>     191     try:
> --> 192         booster = Booster(params=params, train_set=train_set)
>     193         if is_valid_contain_train:
>     194             booster.set_train_data_name(train_data_name)
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\basic.py in __init__(self, params, train_set, model_file, silent)
>    1485             self.handle = ctypes.c_void_p()
>    1486             _safe_call(_LIB.LGBM_BoosterCreate(
> -> 1487                 train_set.construct().handle,
>    1488                 c_str(params_str),
>    1489                 ctypes.byref(self.handle)))
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\basic.py in construct(self)
>     983                                 init_score=self.init_score, predictor=self._predictor,
>     984                                 silent=self.silent, feature_name=self.feature_name,
> --> 985                                 categorical_feature=self.categorical_feature, params=self.params)
>     986             if self.free_raw_data:
>     987                 self.data = None
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\basic.py in _lazy_init(self, data, label, reference, weight, group, init_score, predictor, silent, feature_name, categorical_feature, params)
>     769             self.__init_from_csc(data, params_str, ref_dataset)
>     770         elif isinstance(data, np.ndarray):
> --> 771             self.__init_from_np2d(data, params_str, ref_dataset)
>     772         elif isinstance(data, list) and len(data) > 0 and all(isinstance(x, np.ndarray) for x in data):
>     773             self.__init_from_list_np2d(data, params_str, ref_dataset)
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\basic.py in __init_from_np2d(self, mat, params_str, ref_dataset)
>     833             c_str(params_str),
>     834             ref_dataset,
> --> 835             ctypes.byref(self.handle)))
>     836         return self
>     837 
> 
> D:\Anaconda3\envs\py36\lib\site-packages\lightgbm\basic.py in _safe_call(ret)
>      43     """
>      44     if ret != 0:
> ---> 45         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
>      46 
>      47 
> 
> LightGBMError: Multiclass objective and metrics don't match
>
