### ISSUE TITLE
Why only GBT?

### ISSUE THREAD

**Issue by sodaliAyran** [WillKoehrsen/feature-selector#8]
I understand why you use tree based algorithms to find Zero Importance Features. But why Gradient Boosted Trees is the only option? I think RandomForest and maybe DecisionTree algorithms should be one of the options. Or are they already?

**Comment by WillKoehrsen** [comment]
Random forests would also work for model-based feature importances. This is an option I'm looking to add when I have some time. Thanks for the suggestion.

**Comment by sodaliAyran** [comment]
@WillKoehrsen thank you.
