### ISSUE TITLE
trouble in installation

### ISSUE THREAD

**Issue by rupikat** [WillKoehrsen/feature-selector#9]
how to install feature_selector in ubuntu?

**Comment by WillKoehrsen** [comment]
This should get you installed on any platform

```
git clone https://github.com/WillKoehrsen/feature-selector.git
cd feature-selector
pip install -e .
```

**Comment by zjujdj** [comment]
how to install feature_selector in windows?

**Comment by WillKoehrsen** [comment]
@zjujdj 

```
git clone https://github.com/WillKoehrsen/feature-selector.git
cd feature-selector
pip install -e .
```

**Comment by nvthoang** [comment]
git clone https://github.com/WillKoehrsen/feature-selector.git
cd feature-selector
pip install -e .

I follow these steps but 
"Command "python setup.py egg_info" failed with error code 1 in C:\Users\HOANGN~1\AppData\Local\Temp\pip-install-2fxbqaq0\lightgbm\"

Can you help me with this

**Comment by yuchen3279** [comment]
I tried _pip install feature_selector_ in Anacoda Prompt

And met the same issue with @nvthoang : 
"Command "python setup.py egg_info" failed with error code 1 in C:\Users\Local\Temp\pip-install-n805bq3k\matplotlib\"
 
More detail: 
  * The following required packages can not be built:
                            * freetype, png * Please check http://gnuwin32.sourc
                            * eforge.net/packages/freetype.htm for instructions
                            * to install freetype * Please check http://gnuwin32
                            * .sourceforge.net/packages/libpng.htm for
                            * instructions to install png

I tired to reintall freetype and png, but still shows the same error. Might need help. Thanks

**Comment by VarunMarvah** [comment]
Am also facing similar 2 issues mentioned above , not sure how to proceed

**Comment by Shrav25** [comment]
I am trying to install in Jupyter Notebook, i tried the below codes but seems like its taking a lot of time. I saw two different install commands in this website https://pypi.org/project/feature-selector/

pip install feature-selector

pip install feature_selector

**Comment by thruzd** [comment]
git clone https://github.com/WillKoehrsen/feature-selector.git
cd feature-selector
pip install -e .
comes back as successful but in Jupyter for impor feature_selector I get 
No module named 'feature_selector'
for import feature-selector .. get syntax error got import feature-selector
pip list shows package feature-selector version N-A location my home directory.
any advice?

**Comment by florence27** [comment]
@thruzd having the same trouble as you.

**Comment by XavierJordaMurria** [comment]
same here, it seems that the package gets installed correctly but then in the notebook, there is no way to import it.

**Comment by abhik12295** [comment]
Try to restart kernel or re-open your jupyter notebook after installation. I got the same issue but get resolved after doing this.

@XavierJordaMurria 
@florence27 @thruzd
